version: '3.9'

services:
  playback:
      container_name: playback
      image: playback:latest
      restart: always
      ports:
        - "5555:5555"


  redactor:
      container_name: redactor
      image: redactor:latest
      restart: always
      environment:
        - PLAYBACK_HOST=localhost
        - PLAYBACK_PORT=5555
        - REDACTOR_PORT=5556
      ports:
        - "5556:5556"
      
  visualizer:
      container_name: visualizer
      image: visualizer:latest
      restart: always
      environment:
        - REDACTOR_HOST=localhost
        - REDACTOR_PORT=5556
      depends_on:
        - redactor
      ports:
        - "5556:5556"

